openapi: 3.0.0
info:
  title: User API
  description: User management endpoints, with a test route
  version: 1.0.0
paths:
  /api/user/test:
    get:
      summary: Test route
      tags:
        - User
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Test route is working!"
components: {}
